### ISSUE TITLE
brak obrazka w sekcji dodatki

### ISSUE THREAD

**Issue by pomocnik2** [Developsz/pizzeria42#6]
cześć, zauważyłem w sekcji z dodatkami brakuje obrazka. Zdaje się, że trzeba to poprawić.

**Comment by Developsz** [comment]
commit 6719cb93d5f9cab2ad4fa8cbb25089b2529655cc naprawia ten błąd

**Comment by Developsz** [comment]
6719cb93d5f9cab2ad4fa8cbb25089b2529655cc fixes #6
